[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "3mTs3YNzFV9g3dgQb1FDdarKDtrVcMq2qZE1pfgiuF8P"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
