[package]
name = "create_token"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.5.7"
mpl-token-metadata = "5.1.0"
solana-program = "2.3.0"
spl-associated-token-account = "7.0.0"
spl-token = "8.0.0"

[lib]
crate-type = ["cdylib", "lib"]
